# Add this to your repo to enable secret scanning on Pull requests
name: Secret Scanning Template

on:
  pull_request:

jobs:
  secret_scanning:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/action-secret-scanning@v1
        id: call_trufflehog
        continue-on-error: true
      - uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc
        if: steps.call_trufflehog.outcome != 'success'
        with:
          message: |
            🚨🚨🚨 Secret found 🚨🚨🚨
            Please review your commit
      - name: Fail workflow if secret detected
        if: steps.call_trufflehog.outcome != 'success'
        run: exit 1
