# Add this to your repo to enable secret scanning on Pull requests
name: Secret Scanning Template

on:
  pull_request:

jobs:
  secret_scanning:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/action-secret-scanning@v1
        id: call_trufflehog
